version: "3.8"
services:
  database:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

  tomcat:
    image: tomcat:9.0
    environment:
      - DEBATR_DATABASE_USER=postgres
      - DEBATR_DATABASE_PASSWORD=password
      - DEBATR_DATABASE_URI=postgresql://database:5432/debatr
    volumes:
      - "./target/Debatr-1.0-SNAPSHOT.war:/usr/local/tomcat/webapps/debatr.war"
    ports:
      - "8080:8080"