version: "3.8"
services:
  database:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

  tomcat:
    image: tomcat:9.0
    env_file:
      - .env
    volumes:
      - "./target/Debatr-1.0-SNAPSHOT.war:/usr/local/tomcat/webapps/debatr.war"
    ports:
      - "8080:8080"